#!/usr/bin/env zsh
# shellcheck shell=bash

function lp {
	local ls_path=${1:-.}

	if [ "$OSSYSTEM" = "MacOS" ]; then
		CLICOLOR_FORCE=1 ll "$ls_path" | less -R
	else
		ll --color "$ls_path" | less
	fi

}
