" Environment Setup
" =================
set nocompatible
set runtimepath+=~/.vim/bundle/Vundle.vim
set runtimepath+=/usr/local/lib/python3.4/dist-packages/powerline/bindings/vim


" Vundle Settings
" ===============
filetype off
call vundle#begin()

" let Vundle manage Vundle
Plugin 'gmarik/Vundle.vim'

" File Types
Plugin 'evanmiller/nginx-vim-syntax'
Plugin 'wting/rust.vim'
Plugin 'rodjek/vim-puppet'

" Revision Control
Plugin 'tpope/vim-fugitive'

" View
Plugin 'scrooloose/nerdtree'

" End Vundle Loader
call vundle#end()
filetype plugin indent on


" powerline
" ==========
set laststatus=2
set noshowmode


" editor look
" ===========
set number
set showcmd
set incsearch
set hlsearch
set nowrap


" whitespace
" ==========
set list
set listchars=eol:‹,tab:›\ ,trail:·,extends:»,precedes:«,nbsp:¬


" tabs
" ====
set autoindent
set noexpandtab
set copyindent
set preserveindent
set softtabstop=0
set shiftwidth=4
set tabstop=4


" inputs
" =====
set mouse=a


" syntax
" ======
syntax on

