" Environment Setup
" =================

set nocompatible
if has('python3')
	python3 from powerline.vim import setup as powerline_setup
	python3 powerline_setup()
	python3 del powerline_setup
endif


" Plugin Settings
" ===============

call plug#begin('~/.vim/plugged')

" Usage
"Plug 'ctrlpvim/ctrlp.vim'
"Plug 'scrooloose/nerdcommenter'
"Plug 'moll/vim-bbye'

" File Types
"Plug 'evanmiller/nginx-vim-syntax'
Plug 'wting/rust.vim'
"Plug 'rodjek/vim-puppet'

" Revision Control
"Plug 'tpope/vim-fugitive'

" View
"Plug 'scrooloose/nerdtree'

" Finished
call plug#end()


" powerline
" ==========

set laststatus=2
set showtabline=2
set noshowmode


" editor look
" ===========

set number
set showcmd
set nowrap


" editor functionality
" ====================

" set undofile
set hidden
"set splitbelow
"set splitright
set backspace=indent,eol,start


" search
" ======

"nnoremap / /\v
"vnoremap / /\v
set ignorecase
set smartcase
"set gdefault
set incsearch
set hlsearch


" whitespace
" ==========

set list
set listchars=eol:‹,tab:›\ ,trail:·,extends:»,precedes:«,nbsp:¬


" tabs
" ====

set autoindent
set noexpandtab
set copyindent
set preserveindent
set softtabstop=0
set shiftwidth=4
set tabstop=4


" inputs
" =====

set mouse=a


" mappings
" ========

" cmap w!! w !sudo tee > /dev/null %
let mapleader = ","

" buffers/windows
nnoremap <leader>n :bnext<Enter>
nnoremap <leader>p :bprevious<Enter>
nnoremap <leader>c :bprevious\|bdelete #<Enter>

" copy/paste
vnoremap <leader>y "+y
vnoremap <leader>d "+d
" note: i_ctrl-q is an alternative to i_ctrl-v
" inoremap <C-v> <C-r><C-p>+

" misc
nnoremap <leader><space> :noh<Enter>


" syntax
" ======

syntax on
